const quotes = {
    "maaliv": [
        "Yo mama's so fat, when she fell I didn't laugh, but the sidewalk cracked up.",
        "Yo mama's so fat, when she skips a meal, the stock market drops.",
        "Yo mama's so fat, it took me two buses and a train to get to her good side.",
        "Yo mama's so fat, when she goes camping, the bears hide their food.",
        "Yo mama's so fat, if she buys a fur coat, a whole species will become extinct.",
        "Yo mama's so fat, she stepped on a scale and it said: \"To be continued.\"",
        "Yo mama's so fat, I swerved to miss her in my car and ran out of gas.",
        "Yo mama's so fat, when she wears high heels, she strikes oil.",
        "Yo mama's so fat, she was overthrown by a small militia group, and now she's known as the Republic of Yo Mama.",
        "Yo mama's so fat, when she sits around the house, she SITS AROUND the house.",
        "Yo mama's so fat, her car has stretch marks.",
        "Yo mama's so fat, she can't even jump to a conclusion.",
        "Yo mama's so fat, her blood type is Ragu.",
        "Yo mama's so fat, if she was a Star Wars character, her name would be Admiral Snackbar.",
        "Yo mama's so fat, she brought a spoon to the Super Bowl.",
        "Yo mama's so stupid, she stared at a cup of orange juice for 12 hours because it said \"concentrate.\"",
        "Yo mama's so stupid when they said it was chilly outside, she grabbed a bowl.",
        "Yo mama's so stupid, she put lipstick on her forehead to make up her mind.",
        "Yo mama's so stupid, when they said, \"Order in the court,\" she asked for fries and a shake.",
        "Yo mama's so stupid, she thought a quarterback was a refund.",
        "Yo mama's so stupid, she thought a quarterback was a refund.",
        "Yo mama's so stupid, she got hit by a parked car.",
        "Yo mama's so stupid, when I told her that she lost her mind, she went looking for it",
        "Yo mama's so stupid when thieves broke into her house and stole the TV, she chased after them shouting \"Wait, you forgot the remote!\"",
        "Yo mama's so stupid, she went to the dentist to get a Bluetooth.",
        "Yo mama's so stupid, she took a ruler to bed to see how long she slept.",
        "Yo mama's so stupid, she got locked in the grocery store and starved to death.",
        "Yo mama's so stupid, when I said, \"Drinks on the house,\" she got a ladder.",
        "Yo mama's so stupid, it takes her two hours to watch 60 Minutes.",
        "Yo mama's so stupid, she put airbags on her computer in case it crashed.",
        "Yo mama's so ugly, she threw a boomerang and it refused to come back.",
        "Yo mama's so old, her social security number is one.",
        "Yo mama's so ugly, she made a blind kid cry.",
        "Yo mama's so ugly, her portraits hang themselves.",
        "Yo mama's so old, she walked out of a museum and the alarm went off.",
        "Yo mama's teeth are so yellow when she smiles at traffic, it slows down.",
        "Yo mama's armpits are so hairy, it looks like she's got Buckwheat in a headlock.",
        "Yo mama's so ugly, when she was little, she had to trick-or-treat by phone.",
        "Yo mama's so ugly, her birth certificate is an apology letter.",
        "Yo mama's so ugly, she looked out the window and was arrested for mooning.",
        "Yo mama's so poor, the ducks throw bread at her.",
        "Yo mama's so poor, she chases the garbage truck with a grocery list.",
        "Yo mama's cooking so nasty, she flys got together and fixed the hole in the window screen.",
        "Yo mama's so depressing, blues singers come to visit her when they've got writer's block.",
        "Yo mama's so short, you can see her feet on her driver's license.",
        "Yo mama's so poor, she can't even afford to pay attention.",
        "Yo mama so big, her belt size is \"equator.\"",
        "Yo mama's so classless, she's a Marxist utopia.",
        "Yo mama so short, she went to see Santa and he told her to get back to work.",
        "Yo mama so scary, the government moved Halloween to her birthday.",
        "Yo mama's so nasty, they used to call them jumpolines 'til yo mama bounced on one.",
        "Yo mama's teeth so yellow, I can't believe it's not butter.",
        "Yo mama's so poor, Nigerian princes wire her money.",
        "Yo mama so dumb, she went to the eye doctor to get an iPhone.",
        "Yo mama's so lazy, she stuck her nose out the window and let the wind blow it."
    ],
    "machmi": [

        "Contrary to popular belief Yo mama, not the Florida Supreme Court, made the final judgement on Terri Schiavo's fate. It was a roundhouse kick to the feeding tube.",
        "A mighty crack was heard around the world as Yo mama roundhouse kicked the supercontinent, Pangaea, beginning continental drift.",
        "Yo mama doesn't understand why you should consult your doctor if your erection lasts for more than 4 hours. His erections have been known to last for up to 15 days.",
        "Yo mama doesnt look at the toilet paper after he wipes.",
        "Yo mama throws midgets for fun. He used to do it competitively, but it all ended horribly when he killed the pope.",
        "Someone once tried to assassinate Yo mama's beard but missed hitting Chuck in the face, Chuck proceeded to beat the holy hell out of the guy using nothing but his penis and elbow, Chuck has since installed security on his beard, with a deflector diverting bullets to his face, since he values his beard more than even his rugged good looks.",
        "Yo mama can kill a dog in 7 ways, 4 of which involve throwing missiles at it.",
        "Yo mama once went to jail. The morning after his first night all the inmates, all the guards, and the warden had bleeding assholes.",
        "Yo mama lucky number is one, becuase thats how many tries it takes him to accomplish any task.",
        "If you ever get the chance to play Yo mama in Madden football, he will beat you 56-7.",
        "Yo mama refers to himself in fourth person.",
        "Yo mama told that one kid from the Sixth Sense that he has AIDS. He then smiled.",
        "Artificial insemination was invented when, during an intense and vigorous masturbation session, Yo mama' high velocity ejaculate penetrated a woman's vagina from a quarter of a mile away.  ",
        "Yo mama once killed a man with his bare hands. He then revived him with his bare hands only to end his life with a roundhouse kick to the face.",
        "Yo mama killed Mcgyver by making a set of nun-chucks using newspaper, two toothpicks, a womans weave, and a 3 legged dog.",
        "Yo mama' penis is so large, that he in fact has to tie it around his left leg so that it doesn't get in the way of his round-house kick.",
        "Yo mama once leaned against a tower in Pisa, Italy.",
        "Yo mama can juggle 12 bar stools when drunk but only 8 when sober.  ",
        "Yo mama invented racism because he thought the world was filled with ",
        "Yo mama once ate a bad cheese burger at McDonalds. So he tracked down the president of the company, and round house kicked his secretary in the face so hard that she released her bowels onto the office floor. He then force fed the McDolands president the entire mess. This meal is now considered a delicacy in certain parts of the world, and can be found in certain McDonalds establishments under the name ",
        "There was once a line of soap based off of Yo mama. His face was on every bar. While popular in the early 90s, the soap was discontinued after thousands of women started growing his stern yet sexy beard.",
        "Yo mama built the equator to get a leg up on China's ",
        "In an attempt to follow in the steps of Dolly Parton, Yo mama attempted to open a theme park. Unfortunetly the idea was cast asunder when the name ",
        "There are three ways to do things. The right way, the wrong way and the Yo mama way. The Yo mama way is just the wrong way but with more roundhouse kicks.",
        "Chuck has 5 letters. Norris has 6. When placed together we get 56. 1956 was the year of the first airborn nuclear test. Coincidence? I think not.",
        "Yo mama invented death just so he could kill people.",
        "Before Yo mama, it used to take the Earth 365 days to revolve around the sun. Then in the fall of 1976, Yo mama performed a roundhouse kick so powerful, the shockwave caused the Earth to slow and since then it now takes the Earth 365 and 1/4 days to revolve around the sun. Yo mama is the reason we recognize leap years.",
        "The LA riots where not caused by the Rodney King verdict, they were actually started when Yo mama let the ",
        "Yo mama created the Total Gym by physically beating a Ford Pinto into the shape he had in his mind.  The gas tank did explode during the procedure, but not so much as one hair of Yo mama's beard was singed.",
        "To keep is his mind sharp Yo mama plays Tic-Tac-Toe versus himself. He wins every time.",
        "Yo mama wore jeans so tight his wife became sterile.",
        "Yo mama was on a season of Survivor once, but the entire season got cut after Yo mama murdered everyone on the island for eating his Cheetos.",
        "Yo mama occasionally has Missing In Action flashbacks where he's escaping a Vietnam Prison and randomly starts killing Asians with his bare fist because thats the way Chuck rolls. You'll know when it's coming because Asians start flying through the air with random explosions, horrible subtitles will scroll your line of vision, and  Chuck will run and hide in your mom's garden, finally stealing your Kia Sportage screaming, ",
        "When asked his opinion about the war in Iraq, Yo mama said ",
        "Someone once approached Yo mama suggesting that rearranging the letters in his name reveals the message ",
        "Yo mama once crushed a school bus full of children with his forehead.",
        "Yo mama always keeps a Werther's Original in his jean pocket... For the kids.",
        "Yo mama was playing Tekken 5 one day and finally met his match. His 12-year old son beat him with Eddy Gordo by randomly pressing buttons. Yo mama then roundhouse kicked his son in the throat killing him instantly. That night Yo mama ate well... He ate well indeed...",
        "Yo mama is how the West was won.",
        "Jupiter's Great Red Spot isn't a storm. It's where Yo mama puts his victims.",
        "Yo mama eats Viagra only so that he can have an extra loaded weapon on him at all times.",
        "Yo mama was once held prisoner back in 'Nam. Chuck plucked a hair from his beard, picked a booger and combined them together to create a grenade launcher and killed every soldier in the prison. Once he was back in America he told his story at a bar. A desperate producer overheard his story and a light bulb lit up in his head. That night MacGyver was born.",
        "Yo mama found Nemo.",
        "Yo mama shot at 50 Cent 9 times, but didn't finsh him because he wanted to do it with a roundhouse kick to the face. But 50 Cent ran in horror.",
        "Yo mama once juggled a soccer ball 2,357 times... with just his penis.",
        "Yo mama can travel through time by running at 88 miles per hour.",
        "Yo mama once roundhouse kicked a man into next week. He then roundhouse kicked himself into next week, so he could roundhouse the man another week forward.",
        "Yo mama' family crest is a picture of a baracudda eating Neil Armstrong.",
        "Few people are aware that Yo mama is the first person to ever be diagnosed with beard cancer. Upon hearing this, Yo mama quickly beat the cancer into remission with a series of roundhouse kicks and rabbit punches.",
        "Prince initially called ",
        "Not many people know this but, Walker - Texas Ranger is actually a hidden camera show on Yo mama's life.",
        "Congress is in the process of passing a bill to clone Yo mama for military purposes. They want his genes, particularly because Yo mama' eyes offer nightvision and 3x zoom capabilities.",
        "Yo mama actually invented peanut butter, but while in transit to the patent office, George Washington Carver knocked him unconscious with the aid of chloroform and stole his patent. For revenge, Yo mama threw 7 freight trains on top of George Washington Carver. He died from this.",
        "Yo mama is ranked 12th in the AP college football poll.",
        "If an EMP were to go off within a close proximity of Yo mama, he would be rendered useless for a short period of time, because over 500 years ago, he traded the ability to see the future to Nostradamus for cybernetic arms, legs, and heart.",
        "The title song ",
        "Yo mama tought everyone in Texas karate, so it would look cooler when he kicked their ass on TV.",
        "Everyone respects Yo mama so much, that when they fight him, they politely wait in turn for him to beat them up.",
        "Yo mama once broke the kneck of a passing stranger in the street. When asked why he responded, ",
        "One day Yo mama was infact killed when he round house kicked someone in the face so hard that it shattered the universe. But in heaven, Chuck challenged God to an arm wrestling match. Chuck won, and the universe was reformed.",
        "Yo mama once boned the Mona Lisa, which is why she smiles.",
        "If you knock three times on a wooden object and shout the name of Yo mama with a lisp on your voice, he will appear to you and personally kick your ass. And it will be better than any orgasm you will ever experience.",
        "Yo mama auditioned for the role of Albus Dumbledore for the movie ",
        "Yo mama actually invented the ",
        "Yo mama once passed a kidney stone the size of a baseball. The stone is on display as a moon rock at NASA.",
        "Yo mama stole your bike.",
        "Yo mama believes strongly in ending world hunger. He plans to do this by terminating the populations of all third world countries.",
        "Yo mama is actually the love child of Willie Nelson and an mystical ninja mummy.",
        "A ducks quack does not echo. Yo mama is solely responsible for this phenomenon. When asked why he will simply stare at your grimly.",
        "Hellen Keller's favorite color is Yo mama.",
        "In an attempt to bolster ratings during sweeps week in 1988, CNN began referring to itself as the ",
        "It is Yo mama' eye that adorns the Great Seal on the back of the $1 bill. He is all seeing.",
        "Yo mama IS the ",
        "Ask not what Yo mama will do for a Klondike bar, ask what the Klondike bar will do for Yo mama.",
        "Yo mama is both blessed and cursed with the ability to destroy anything by merely by looking at it. To prevent this from happening, Chuck personally removed his eyes and now uses Bob Saget as the stick blind persons use to locate objects in their path. He can also use incredibly high pitched Karate screams as sonar.",
        "The shadow from Yo mama' mustache can accurately predict the length of winter to within 4 seconds. The groundhog has been rendered obsolete.",
        "The song ",
        "Ever wonder where ",
        "On the sixth day God created Yo mama.",
        "Contrary to popular belief, Yo mama was dropped at Hiroshima and Nagasaki.",
        "Yo mama does not see dead people. He eats them.",
        "Yo mama and Steven Seagal are secretly married. Norris wears the pants.",
        "Walker Texas Ranger is just a normal man, but when danger calls he transforms into Yo mama.",
        "The ",
        "Yo mama was taking and evening stroll in a local neighborhood when a mountain spring water truck slammed in to a retarded child playing in the street. Yo mama rushed to the scene, destroyed the driver, and resurrected the child making him normal again. This event is celebrated as a show on TV called Captian Planet.",
        "Yo mama was once accused of heresy by the Pope, but as it turns out, Yo mama is, in fact, the true son of god.",
        "Yo mama is so awesome, he made the Bob Saget fact generator cease to exist. ",
        "Yo mama' heart beats once every week.",
        "One time Yo mama got bored so he flew to England and orally sodomized the entire royal family.",
        "The original theme song to the Transformers was actually ",
        "Yo mama was the first person to climb Mount Everest. Naked.",
        "One day Yo mama went shopping and he had grabbed the last can of pea soup off the counter. Just then Steven Segal, Jean-Claude Van Damme, and Godzilla walked in and turned to Yo mama and said, ",
        "Yo mama spread the belief that women do not take shits... I believe him.",
        "Yo mama goes to the toilet once a month, if he needs to or not.",
        "Yo mama once fed a starving Ethiopian boy a 12 course meal, then promptly sacrificed the boy to Satan in an effort to boost the ratings of Walker Texas Ranger.",
        "Yo mama is the worlds best actor because his moustache is  the worlds best acting coach.",
        "Yo mama once made love to a Sasquatch. This resulted in the birth of George W. Bush, and the Sasquatch contacting an incurable form of Syphillis, known as ",
        "Yo mama has every copy of National Geographic in his basement. He also has the ability to lift every single one of them at once.",
        "In his spare time, Yo mama breeds thoroughbred horses by manually inseminating the females with his own semen.",
        "Yo mama once injested Pop Rocks while drinking Coke, and lived to tell about it. He then proceeded to bitch slap the Pope for saying how much Walker Texas Ranger sucked.",
        "There's no such thing as a tornado. Yo mama just hates trailer parks.",
        "To Yo mama, doorknobs and urination are seen as merely suggestions.",
        "Yo mama can piss on the third rail and not get electrocuted.",
        "Whereas most people are killed by a BAC of .45, Yo mama only passes out when the alcohol in his veins is less than 5% blood.",
        "In response to his challenge, Yo mama roundhouse kicked MC Hammer so hard that he went bankrupt. Chuch Norris then bellowed, ",
        "Yo mama once tamed a wild stallion in the forest. He rode the horse across the United States and back in under 24 hours. When he returned home he killed the horse and ate the entire thing.",
        "When he was a baby, Yo mama dropped his mother on her head. She never refused her breast milk to him again.",
        "Yo mama loves cute little puppies. He especially loves them on rye with some pepper jack and a dash of paprika.",
        "Yo mama once held an anti-government protest in Washington. At the news, the government was so terrified that it disbanded immediately and declared Chuck the new President. Though pleased, Chuck's only intent had been to lure in dirty hippies to kick their asses.",
        "Yo mama first appeared on TV when he was 8 years old, doing a musical number on the show 'Star Search'.  When Yo mama' musical number started he just roundhouse kicked one of the judges in the face.  He then remained motionless for the last two minutes of the song while smiling and giving the thumbs up.  Yo mama would have won but, due to paralysis, judge number three just made gurgling noises when he tried to tell Yo mama he received a perfect score.",
        "When Yo mama was interviewed by local papers as to why he saved the baby from the fire he replied, ",
        "The Ice Age is contributed to Yo mama, that was the date of his last erection which blocked the sun's rays for 47 years.",
        "Vin Diesel has only had one nightmare in his lifetime. It involved Yo mama, and his murderous group of Oompa-Loompas.",
        "Yo mama cannot be seen without 4-D vision glasses. His beard requires 5-D vision glasses and sun screen.",
        "Yo mama never showers... because he never breaks a sweat.",
        "An entire episode of Walker, Texas Ranger was shot with the lens cap on. This made no difference, however, because the light emanating from Yo mama' beard permeated the plastic cap and allowed the camera to see Chuck in all his glory.",
        "Yo mama circumcised himself. At birth. With his bare hands.",
        "Yo mama ties dead puppies to his feet to simulate real blood spraying from the faces of his stunt actors.",
        "Yo mama went to a fortune teller once. She predicted pain.",
        "Yo mama once flushed himself down a toilet to fight an allegator. After defeating the beast with one swift round house kick, he went home to eat his neighbor's children.",
        "Yo mama was the first human to willingly snort anthrax, all he did was sneeze and out came Steven Seagal and Jet Li.",
        "Yo mama doesn't experience miricales, he makes them.",
        "Yo mama appeared in the movie Pearl Harbor in a cameo role as a palm tree. An ass-kicking, fire-breathing palm tree. Most of his scenes were cut, due to time and credibility restraints, since nobody could believe that Chuck could be within 500 yards of Ben Affleck without doing him serious bodily harm.",
        "Once Yo mama made Jean Claude Van-Damme cry just by staring at him.",
        "When asked if videogame-related violence was a threat to America's children, Yo mama promptly roundhouse kicked Jack Thompson in the face. Ironically, moments later two 13-year-olds were found dead less than a mile from the scene, attempting to reenact this stunt.",
        "Yo mama eats tiger hearts every morning for strength, power, and wisdom. He eates men's hearts for sport.",
        "The the Geneva Convention specifically forbids the use of Yo mama in an international conflict.",
        "Yo mama knows Steven Segall personally. He is made up of the corn in Yo mama' fecal matter.",
        "Booze gains alcohol content after passing through Yo mama.",
        "Yo mama CAN find a needle in a haystack, and then kill a man with the needle... or the haystack.",
        "Yo mama was once taking a dump in a public bathroom in New York, and at one point, the man in the next stall made a comment about the horrible stench of Chuck's feces. Norris proceeded to release a bout of flatulence that incinerated the poor fool shitting next to him, and then recounted his story to a scientist friend of his, who did some further research. The basis for the atom bomb was discovered, and the research was called ",
        "Each year, Yo mama brings gifts to people across the world as compensation for killing one of their loved ones. We know this day as Christmas.",
        "Yo mama has 118,453 friends on myspace. It is an unspoken agreement that when you join his list of friends, you are actually placing your name on his list of death, but Yo mama' friends do not care. To die by the hand of Chuck is an honor.",
        "Yo mama is the only man to never use an eraser.",
        "Yo mama hates internet piracy but he also loves his fans. If he ever catches you downloading episodes of Walker: Texas Ranger, his conflicting opinions mean that he has to shake your hand and beat you senseless at the same time.",
        "Tony Danza reports to Yo mama.",
        "Yo mama constructed his own iPod by staring intensely at 10,000 country-western bands until they fearfully compacted themselves into a 2x4x1/2 inch white rectangle.",
        "Why did the chicken cross the road? Because Yo mama ate its entire family, killed the farmer who bred it, and sex with the famers' wife all at the same time.",
        "Rumors falsely claim that b29 bombers dropped the atom bombs on Japan. The truth is that Yo mama threw the bomb all the way to Hirosima.",
        "Due to the excessive amount of unprotected sex Yo mama takes part in, it is garunteed that he appears in your family tree anywhere from 3 to 10 times.",
        "Yo mama is so cool that the Pope has a Jesus fish on his car with the word ",
        "Yo mama knew the ",
        "Yo mama knows where in the world Carmen Sandiego is, but he won't tell because he doesn't want anyone to find the body.",
        "Yo mama knows all the numbers of pi, but will only share them if he can be beaten in hand-to-hand combat. This is why we have supercomputers trying to figure it out instead.",
        "Upon hearing of the possible outbreak of Bird Flu, Yo mama became outraged and announced he will kill off every species of bird. When asked about his statement, he replied, ",
        "Yo mama once beat Mike Tyson's Punch Out in the desert while trimming red hair from his taint with a box cutter. What? You say there are no outlets for the Nintendo in the desert? Tell that to Yo mama.",
        "The only person that can kill Yo mama is Yo mama. He is waiting until he runs out of other people to kill.",
        "Yo mama will never ",
        "It is a commonly held belief of the Jewish faith that, as a mere babe, Yo mama was separated from his mother in a blizzard. To this day, he hates snow so much that he roundhouse kicks each individual snowflake. The concussive force makes them all unique.",
        "Yo mama was recently credited with finding a new race of people living in his chest hair.",
        "The Fantastic 4 was originally The Fantastic 5 until Yo mama was kicked out for raping the Invisible Woman.",
        "Yo mama doesn't need oxygen. He only inhales in order to absorb the ashes of his enemies in his lungs. And exhaling? That's because he doesn't want to shit.",
        "One time a bee tried to sting Yo mama. He just laughed at it and blew it up with his laser vision.",
        "Yo mama listens to Pantera to calm down.",
        "Yo mama' sperm can penetrate 13 condoms, the birth control pill, a brick wall, and the 1975 Pittsburgh Steelers offensive line in order to impregnate a woman.",
        "God is Yo mama' prototype.",
        "Yo mama can read every AIM conversation for they are stored on the infinite hard drive of his computer.",
        "Yo mama embodies the only matter known to have escaped a black hole.",
        "Yo mama' Blood Alcohol Level is continously 8.0, but he is always fine to drive.",
        "Yo mama burned his eyeballs out with cigartettes just to prove to some grade eight students that smoking is dangerous.",
        "The tide rises when Yo mama tells it to.",
        "Stores will accept Monopoly money if Yo mama is paying.",
        "Yo mama' laugh sounds like that of a small child. You wouldn't know this because he never laughs.",
        "Jimmy Hoffa is alive and well in Yo mama' large intestine but refuses to say ",
        "Yo mama does not get frostbite. Yo mama bites frost.",
        "Yo mama was once fined $1,000 for drawing Native American war symbols in invisible ink on the canvases of the Metropolitan Museum of Art's Impressionist wing.",
        "Yo mama created whiskey to help control the Indians.",
        "Oxygen requires Yo mama to live.",
        "Yo mama once had a head on collision with the sun. Luckily, the sun is so far away that the shift of its position had no effect on Earth.",
        "Yo mama has actually visited the moon on four separate occasions, each time saving Mars by jump kicking through the windscreen of communist shuttles and punching Stalin clones in the ovaries.",
        "If you want to wear the same cologne as Yo mama, you'll be disappointed to find that Yo mama doesn't wear cologne. For two hundred dollars, however, Mr. Norris will fart on your chest before you go on a date.",
        "Some people believe UFOs fly around so erratically because they are trying to impress us. However, they are just trying to get away from Yo mama. The crash of 1947 showed the aliens that Earth would not be so easy to subdue.",
        "Yo mama plays marbles with grenades.",
        "Yo mama requires no stunt double, however his beard has stood in for the actor that played Chewbacca on many occasions.",
        "Yo mama' bones cannot be broken by anyone except Yo mama. Sometimes Chuck breaks his own bones just to show off.",
        "Cars were invented to have a faster way of fleeing from Yo mama. Not to be outdone, Yo mama invented the car accident.",
        "In order to shave, Yo mama would need a special razor made out of adamantium. The economic decline of the Carter administration caused the manufacturing of these razors to be too expensive, hence Yo mama now wears a beard.",
        "The last person to challenge Yo mama to a hand-to-hand combat later became to founder of War-Amps.",
        "Yo mama killed Rudolph, Donner, and Blitzen because they didnt join in any reindeer games.",
        "Praying Mantises take after Yo mama. After having sex they bite off the head of their mate.",
        "Yo mama was born a blonde, but the blood of his victims dyed his hair and beard to a healthy orange.",
        "NASA hired Yo mama to save money. He kicks people into outer space, and they later land safely into his chest hair.",
        "Yo mama removed his own tonsils. He didn't even have tonsillitis.",
        "For every hour a plane ride takes, Yo mama can get to the destination in that many steps.",
        "Lance Armstrong really didn't lose a testicle to cancer, he is actually the only living survivor to a Yo mama delivered round house kick to the balls",
        "Yo mama once drank so much beer, all of the breweries of the world ran out. And then he started on wine...",
        "When Yo mama enters a night club, he instantly becomes the life of the party. An instant is roughly how long it takes Yo mama to kill a room full of people.",
        "Yo mama does not query the existence of God. God wonders if Yo mama is human, because he sure as hell never created him.",
        "Yo mama once saved 500 people from a burning building in 0.3 seconds. He then proceeded to give each one a fatal round-house kick to the face.",
        "Yo mama once dug his way to the center of the Earth using only a jar of petroleum jelly and his penis.",
        "Yo mama created the first perpetual motion machine by hanging a Volkswagen Beetle on the end of a tetherball pole then kicking it. Thus he solved the world's energy problem.",
        "Yo mama melts dry ice in his pool so he can swim without getting wet.",
        "Yo mama was called to the set of the movie ",
        "At this very moment, there is a 50/50 chance that Yo mama is boning your sister.",
        "Yo mama once took 12 NoDoz pills and then slept for 48 straight hours, just to prove a point.",
        "Yo mama used his bare hands and caught the Road Runner. He then roundhouse kicked Wile E. Coyote for being so incompetent.",
        "When Yo mama found out dolphins were becoming an endangered species, he banged flipper and she gave birth 100 times.",
        "Florida used to be in a straight line, until Yo mama kicked Miami for refusing to make a ",
        "Yo mama snorts battery acid to get a buzz. He claims it tickles.",
        "Every time Yo mama executes a roundhouse kick, the incredible speed at which his leg cuts through the air creates an enormous sonic boom. This is commonly known as ",
        "When on vacation in December of '04 Yo mama was stung by a jelly fish. Delirious with rage at the unadulterated insolence, he roundhouse kicked the ocean into submission. The result nearly wiped out a generation of Thais.   ",
        "Yo mama chiseled the image of Mount Rushmore into his abs with a butter knife.",
        "When Yo mama bleeds, oak trees sprout up from where the blood fell.",
        "Yo mama puts the 'I' in 'Team'",
        "Yo mama promised a Gypsy that he would eat San Francisco when Duke Nukem Forever is released. That's why it has been pushed back so many times.",
        "Yo mama was the inspiration for Donkey Kong, HD-TV, and waterslides. Yes, waterslides.",
        "Once, while traveling in space, a stray asteroid collided with Yo mama' testicles, slicing the left one off. Just to prove that he's badass, he ejaculated with only one testicle to stop the testicle that he didn't have. This event is recreated  in the end of Final Fantasy VII.",
        "Yo mama knows how to pronounce Cthulhu. However, if he says Cthulhu in the correct pronounciation, several Turkmenistanian virgins will be sacrificed to Loki.",
        "Yo mama can penetrate a female from up to a mile away, not psychokinetically, he just has a very large cock.",
        "Yo mama once shot a German plane down with his finger by pointing at it and yelling, ",
        "Yo mama likes Pina Coladas, but fucking hates getting caught in the rain.",
        "One time, Yo mama escaped from Alcatraz with nothing but an elastic band and a plastic fork. This was was the inspiration for the song ",
        "Scientology is Yo mama' first sucessful get-rich-quick scheme.",
        "Yo mama loves the smell of naplam in the morning.",
        "Yo mama knows exactly where Waldo is on every page. Even the pirate one.",
        "Yo mama once ate a whole cheesewheel to show a group of third graders how badass he is.",
        "Yo mama went on a drug trip with Raffi, which resulted in the lyrics for the song ",
        "Once a grizzly bear threatened to eat Yo mama. Chuck showed the bear his fist and the bear proceeded to eat himself, because it would be the less painful way to die.",
        "Yo mama let the dogs out. He has yet released a public apology for his actions.",
        "Yo mama believes that a flamethrower is an essential part of a well balanced breakfast.",
        "The two 'atomic bombs' dropped on Japan in World War Two were actually two small parts of Yo mama' left testicle, which he graciously donated to defeat Hitler and the Axis powers in 1943. Since then he has regenerated said testicle, and in the process made Tim McGraw a bigger douche.",
        "Yo mama eats members of the Ku Klux Klan for lunch every Thursday.",
        "Yo mama shot the sheriff AND the deputy. He then occupied the position of deputy.",
        "Yo mama caught all 386 pokemon in just under 2.7 seconds. He says he won't trade any of them for anything.",
        "The mathematical proof ",
        "One does not punch Yo mama; Yo mama headbutts one's fist.",
        "Yo mama will kick you, and it will hurt. Forever.",
        "Yo mama can stop time for up to two hours by thinking about pineapples",
        "Yo mama punched a woman in the vagina when she didn't give him exact change.",
        "If you shoot Yo mama, you'll only make him angry.",
        "Yo mama once destroyed Tokyo for fun, but was able to rebuild it in a matter of milliseconds.",
        "Yo mama starts his day with a bowl of oatmeal, some pancakes and a glass of fresh squeezed Nazi juice.",
        "Yo mama once fought off 42 ninjas bilndfolded, while having sex with 3 women.",
        "After much debate, President Truman decided to drop the atomic bomb on Hiroshima rather than the alternative of sending Yo mama. His reasoning? It was more ",
        "Yo mama built the entire continent of Asia in two days using just a spoon and Teen People magazine.",
        "Every piece of furniture in Yo mama' house is a Total Gym.",
        "Yo mama and Snoop Dogg once had a free style rap battle so awsome that people now celebrate the holiday Easter to remember the day.",
        "Shortly after Bruce Lee's death, Yo mama worked as a Chemist, during which time he discovered the element of surprise and later, painium. He won a nobel prize for his work which he put next to his imaginary Oscar on his trophy shelf",
        "Yo mama has killed every single person who has ever called him ",
        "Halloween was invented when Yo mama disguised himself as a ghost so that he could beat up a pumpkin, light it on fire, and steal all of its candy.",
        "Yo mama, when clean-shaven, radiates the heat of three suns.",
        "The Internet slang ",
        "Mott's apple juice originally started as an inside joke between Yo mama and his invisible friend. His invisible friend bet him that he couldn't urinate into bottles and sell it to people.",
        "Yo mama can play the solo from ",
        "Yo mama invented the cure for polio when he was bored one day.",
        "If you take Yo mama and subtract the letters i, s, o, r, n, u, c, k, and h, then add the letters j, e, s, u, and s--in that order--you end up with Jesus.",
        "Yo mama is what Willis is talkin' 'bout.",
        "The lead role for The Pacifier was chosen all depending on a game of Counter-Strike between Vin Diesel and Yo mama. Vin Diesel won the game, but only because he was camping. In an angered state of rage, Yo mama notified God and got Vin Diesel banned from Earth. That took him down a peg.",
        "Yo mama knows whether the moon landings were fake or not.",
        "Yo mama was the first person to tame a dinosaur."


    ]
}
