const quotes = {
    "maaliv": [
        "Yo mama's so fat, when she fell I didn't laugh, but the sidewalk cracked up.",
        "Yo mama's so fat, when she skips a meal, the stock market drops.",
        "Yo mama's so fat, it took me two buses and a train to get to her good side.",
        "Yo mama's so fat, when she goes camping, the bears hide their food.",
        "Yo mama's so fat, if she buys a fur coat, a whole species will become extinct.",
        "Yo mama's so fat, she stepped on a scale and it said: \"To be continued.\"",
        "Yo mama's so fat, I swerved to miss her in my car and ran out of gas.",
        "Yo mama's so fat, when she wears high heels, she strikes oil.",
        "Yo mama's so fat, she was overthrown by a small militia group, and now she's known as the Republic of Yo Mama.",
        "Yo mama's so fat, when she sits around the house, she SITS AROUND the house.",
        "Yo mama's so fat, her car has stretch marks.",
        "Yo mama's so fat, she can't even jump to a conclusion.",
        "Yo mama's so fat, her blood type is Ragu.",
        "Yo mama's so fat, if she was a Star Wars character, her name would be Admiral Snackbar.",
        "Yo mama's so fat, she brought a spoon to the Super Bowl.",
        "Yo mama's so stupid, she stared at a cup of orange juice for 12 hours because it said \"concentrate.\"",
        "Yo mama's so stupid when they said it was chilly outside, she grabbed a bowl.",
        "Yo mama's so stupid, she put lipstick on her forehead to make up her mind.",
        "Yo mama's so stupid, when they said, \"Order in the court,\" she asked for fries and a shake.",
        "Yo mama's so stupid, she thought a quarterback was a refund.",
        "Yo mama's so stupid, she thought a quarterback was a refund.",
        "Yo mama's so stupid, she got hit by a parked car.",
        "Yo mama's so stupid, when I told her that she lost her mind, she went looking for it",
        "Yo mama's so stupid when thieves broke into her house and stole the TV, she chased after them shouting \"Wait, you forgot the remote!\"",
        "Yo mama's so stupid, she went to the dentist to get a Bluetooth.",
        "Yo mama's so stupid, she took a ruler to bed to see how long she slept.",
        "Yo mama's so stupid, she got locked in the grocery store and starved to death.",
        "Yo mama's so stupid, when I said, \"Drinks on the house,\" she got a ladder.",
        "Yo mama's so stupid, it takes her two hours to watch 60 Minutes.",
        "Yo mama's so stupid, she put airbags on her computer in case it crashed.",
        "Yo mama's so ugly, she threw a boomerang and it refused to come back.",
        "Yo mama's so old, her social security number is one.",
        "Yo mama's so ugly, she made a blind kid cry.",
        "Yo mama's so ugly, her portraits hang themselves.",
        "Yo mama's so old, she walked out of a museum and the alarm went off.",
        "Yo mama's teeth are so yellow when she smiles at traffic, it slows down.",
        "Yo mama's armpits are so hairy, it looks like she's got Buckwheat in a headlock.",
        "Yo mama's so ugly, when she was little, she had to trick-or-treat by phone.",
        "Yo mama's so ugly, her birth certificate is an apology letter.",
        "Yo mama's so ugly, she looked out the window and was arrested for mooning.",
        "Yo mama's so poor, the ducks throw bread at her.",
        "Yo mama's so poor, she chases the garbage truck with a grocery list.",
        "Yo mama's cooking so nasty, she flys got together and fixed the hole in the window screen.",
        "Yo mama's so depressing, blues singers come to visit her when they've got writer's block.",
        "Yo mama's so short, you can see her feet on her driver's license.",
        "Yo mama's so poor, she can't even afford to pay attention.",
        "Yo mama so big, her belt size is \"equator.\"",
        "Yo mama's so classless, she's a Marxist utopia.",
        "Yo mama so short, she went to see Santa and he told her to get back to work.",
        "Yo mama so scary, the government moved Halloween to her birthday.",
        "Yo mama's so nasty, they used to call them jumpolines 'til yo mama bounced on one.",
        "Yo mama's teeth so yellow, I can't believe it's not butter.",
        "Yo mama's so poor, Nigerian princes wire her money.",
        "Yo mama so dumb, she went to the eye doctor to get an iPhone.",
        "Yo mama's so lazy, she stuck her nose out the window and let the wind blow it."
    ],
    "machmi": [
        "You are awesome",
        "Good Job", 
        "Steve Job",
        "Ok Job not bad"
    ],
    "tunnelStage":[
        "The longest tunnel in the world is the Gotthard Base Tunnel in Switzerland, measuring 35.5 miles (57 kilometers) in length.",
        "The Channel Tunnel, also known as the Eurotunnel, connects England and France and is the longest undersea tunnel in the world, spanning 23.5 miles (37.9 kilometers).",
        "The world's first underground railway, the London Underground, opened in 1863 and is commonly referred to as the Tube.",
        "The Tokyo Bay Aqua-Line in Japan is an underwater tunnel that combines a bridge and tunnel, allowing vehicles to travel over the sea.",
        "The Fréjus Road Tunnel, located between France and Italy, is one of the oldest vehicular tunnels in the world, opened in 1980.",
        "Tunnel boring machines (TBMs) are commonly used for excavating tunnels. They are enormous machines that can be hundreds of meters long and can bore through various types of rock and soil."      

    ],
    "congratulations": [
        "Heartiest felicitations to the triumphant victor of the enthralling snake game!",
        "A profound and resounding congratulation to the exalted conqueror of the serpent realm!",
        "Splendid triumph! Congratulations to the distinguished champion of the serpentine dominion!",
        "A grandiose achievement indeed! Congratulations to the noble victor of the captivating snake game!",
        "Hats off to the brilliant winner who emerged victorious in the captivating snake game!",
        "A momentous conquest! Congratulations to the illustrious champion of the snake game!",
        "An extraordinary feat! Congratulations to the eminent victor of the captivating serpent challenge!",
        "A monumental victory indeed! Congratulations to the honorable winner of the mesmerizing snake game!",
        "Kudos to the consummate champion who emerged victorious in the captivating game of serpents!",
        "A spectacular achievement! Congratulations to the distinguished conqueror of the snake game!",
      ]
}